// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { getDirectDatabaseUrl } from "./lib/database-url";

const databaseUrl = getDirectDatabaseUrl();

if (!databaseUrl) {
  throw new Error(
    "Set DIRECT_DATABASE_URL to a postgres:// URL (from `npm run db:local`). Prisma Studio cannot use prisma+postgres:// URLs.",
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
