// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { getDirectDatabaseUrl } from "./lib/database-url";

const databaseUrl = getDirectDatabaseUrl();

// A direct postgres:// URL is only needed by CLI commands that connect to the DB
// (migrate, db push, studio). `prisma generate` does not, so we omit the datasource
// when no URL is available to avoid breaking installs/builds (e.g. on Vercel where
// only a prisma+postgres:// URL is configured).
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  ...(databaseUrl ? { datasource: { url: databaseUrl } } : {}),
});
